<?php

declare(strict_types=1);

use Drupal\comment\CommentInterface;
use Drupal\Core\Link;

/**
 * Implements hook_preprocess_HOOK() for comment.html.twig.
 */
function wimleers_v3_preprocess_comment(&$variables) {
  /** @var \Drupal\Core\Datetime\DateFormatterInterface $date_formatter */
  $date_formatter = \Drupal::service('date.formatter');

  // Whether to show the manually entered subject or not. Before node 112,
  // manual subjects were enabled, afterwards: not anymore.
  if ($variables['commented_entity']->id() > 112) {
    $variables['title'] = NULL;
  }
  $comment = $variables['comment'];
  assert($comment instanceof CommentInterface);

  // Olivero overrode this to a silly relative time format, which only works well for recent content.
  // Inject into that same variable a permalink (without the prominent "Permalink" link text).
  // 💡 This allows NOT overriding comment.html.twig! 🥳
  $variables['created'] = Link::fromTextAndUrl(
    $date_formatter->format($comment->getCreatedTime(), 'medium'),
    $comment->permalink(),
  )->toString();
}
